"""Validation for the ccf_pipeline package (Phase 1: 'FastMspec' technique).

Primary check compares against a real Octave run of the actual, unmodified
lib/ccf_compute_crosscorr_mtc_Z.m on identical synthetic input -- fixture
generated by octave_verify_ccf/ (see its README.md for how). This is the
same strategy used for thomson_multitaper's own verification.
"""
import numpy as np
import scipy.io as sio
import pytest

from thomson_multitaper import FastMultitaper
from ccf_pipeline import (
    compute_crosscorr_mtc_fastmspec,
    compute_crosscorr_mtc_mspec,
    compute_crosscorr_mtc_mspecbestk,
)

FIXTURE = "../octave_verify_ccf/synth_medium.mat"
MSPEC_FIXTURE = "../octave_verify_ccf/mspec_out.mat"
MSPECBESTK_FIXTURE = "../octave_verify_ccf/mspecbestk_out.mat"


def _load(path):
    try:
        return sio.loadmat(path)
    except FileNotFoundError:
        pytest.skip(f"Octave fixture {path} not present -- run octave_verify_ccf's dry-run first")


def _load_fixture():
    return _load(FIXTURE)


def test_matches_octave_on_onesided_portion():
    mat = _load_fixture()
    s1, s2 = mat["S1"], mat["S2"]
    coh_sum_octave = mat["coh_sum"].squeeze()

    result = compute_crosscorr_mtc_fastmspec(s1, s2, wband=0.05, cutoff=0.95, epsilon=0.05)

    n_samples = s1.shape[2]
    n_onesided = n_samples // 2 + 1
    py_onesided = result.coh_sum[:n_onesided]
    oct_onesided = coh_sum_octave[:n_onesided]

    rel = np.linalg.norm(py_onesided - oct_onesided) / np.linalg.norm(oct_onesided)
    assert rel < 1e-10


def test_reflection_produces_correct_length_unlike_buggy_matlab():
    mat = _load_fixture()
    s1, s2 = mat["S1"], mat["S2"]
    coh_num_octave = int(mat["coh_num"].squeeze())
    coh_sum_octave = mat["coh_sum"].squeeze()

    result = compute_crosscorr_mtc_fastmspec(s1, s2, wband=0.05, cutoff=0.95, epsilon=0.05)

    n_samples = s1.shape[2]
    assert n_samples == 32  # this fixture's N mod 4 == 0, the bug-triggering case
    assert len(result.coh_sum) == n_samples  # correct: two-sided length == N
    assert len(coh_sum_octave) == n_samples + 1  # documents the known upstream bug
    assert result.coh_num == coh_num_octave


def test_reflection_parity_rule_directly():
    from ccf_pipeline.crosscorr_mtc import _reflect_onesided_to_twosided

    for n in [4, 6, 8, 10, 12, 10801, 11, 9, 7, 5, 32]:
        n_onesided = n // 2 + 1
        onesided = np.arange(1, n_onesided + 1) + 1j * np.arange(n_onesided)
        two_sided = _reflect_onesided_to_twosided(onesided, n)
        assert len(two_sided) == n


def test_taper_size_matches_octave():
    mat = _load_fixture()
    s1, s2 = mat["S1"], mat["S2"]
    result = compute_crosscorr_mtc_fastmspec(s1, s2, wband=0.05, cutoff=0.95, epsilon=0.05)
    # taper_size = 4, confirmed by the Octave run recorded in octave_verify_ccf/README.md's
    # underlying dry-run output (not stored in the .mat fixture itself)
    assert result.taper_size == 4


def test_mspec_matches_octave():
    fix = _load_fixture()
    s1, s2 = fix["S1"], fix["S2"]
    mat = _load(MSPEC_FIXTURE)
    coh_octave = mat["coh_sum"].squeeze()

    result = compute_crosscorr_mtc_mspec(s1, s2, wband=0.05, dt=1.0)
    assert result.taper_size == 3

    n_samples = s1.shape[2]
    n_onesided = n_samples // 2 + 1
    rel = np.linalg.norm(result.coh_sum[:n_onesided] - coh_octave[:n_onesided]) / np.linalg.norm(
        coh_octave[:n_onesided]
    )
    assert rel < 1e-10
    assert len(result.coh_sum) == n_samples  # fixed length, vs octave's buggy n_samples+1


def test_mspecbestk_matches_octave():
    fix = _load_fixture()
    s1, s2 = fix["S1"], fix["S2"]
    mat = _load(MSPECBESTK_FIXTURE)
    coh_octave = mat["coh_sum"].squeeze()

    result = compute_crosscorr_mtc_mspecbestk(s1, s2, wband=0.05, cutoff=0.95, epsilon=0.05, dt=1.0)
    assert result.taper_size == 2  # FastMultitaper(32,0.05,0.95,0.05).K

    n_samples = s1.shape[2]
    n_onesided = n_samples // 2 + 1
    rel = np.linalg.norm(result.coh_sum[:n_onesided] - coh_octave[:n_onesided]) / np.linalg.norm(
        coh_octave[:n_onesided]
    )
    assert rel < 1e-10
    assert len(result.coh_sum) == n_samples


def test_t_style_fastmspec_injected_fmtse_matches_octave():
    """T's calling convention: a pre-built FastMultitaper injected via
    fmtse=, matching ccf_compute_crosscorr_mtc_T.m's filttype.FMTSE usage,
    verified against a real run of that actual .m file (not _Z.m)."""
    fix = _load_fixture()
    s1, s2 = fix["S1"], fix["S2"]
    mat = _load("../octave_verify_ccf/t_fastmspec_out.mat")
    coh_octave = mat["coh_sum"].squeeze()

    n_samples = s1.shape[2]
    fmtse = FastMultitaper(n_samples, 0.05, 0.95, 0.05)
    result = compute_crosscorr_mtc_fastmspec(s1, s2, fmtse=fmtse)
    assert result.taper_size == 4

    n_onesided = n_samples // 2 + 1
    rel = np.linalg.norm(result.coh_sum[:n_onesided] - coh_octave[:n_onesided]) / np.linalg.norm(
        coh_octave[:n_onesided]
    )
    assert rel < 1e-10


def test_t_style_mspec_direct_nw_ktaps_matches_octave():
    """T's calling convention: nw/k_taps read directly from config rather
    than derived from wband, matching ccf_compute_crosscorr_mtc_T.m's
    filttype.NW_mspec/K_taps_mspec, verified against a real run of _T.m."""
    fix = _load_fixture()
    s1, s2 = fix["S1"], fix["S2"]
    mat = _load("../octave_verify_ccf/t_mspec_out.mat")
    coh_octave = mat["coh_sum"].squeeze()

    result = compute_crosscorr_mtc_mspec(s1, s2, nw=2.0, k_taps=3, dt=1.0)
    assert result.taper_size == 3

    n_samples = s1.shape[2]
    n_onesided = n_samples // 2 + 1
    rel = np.linalg.norm(result.coh_sum[:n_onesided] - coh_octave[:n_onesided]) / np.linalg.norm(
        coh_octave[:n_onesided]
    )
    assert rel < 1e-10


if __name__ == "__main__":
    import sys

    tests = [
        test_matches_octave_on_onesided_portion,
        test_reflection_produces_correct_length_unlike_buggy_matlab,
        test_reflection_parity_rule_directly,
        test_taper_size_matches_octave,
        test_mspec_matches_octave,
        test_mspecbestk_matches_octave,
        test_t_style_fastmspec_injected_fmtse_matches_octave,
        test_t_style_mspec_direct_nw_ktaps_matches_octave,
    ]
    failures = 0
    for t in tests:
        try:
            t()
            print(f"PASS {t.__name__}")
        except AssertionError as exc:
            failures += 1
            print(f"FAIL {t.__name__}: {exc}")
        except Exception as exc:  # e.g. skip
            print(f"SKIP/ERROR {t.__name__}: {exc}")
    print()
    print("ALL PASS" if not failures else f"{failures} FAILURE(S)")
    sys.exit(1 if failures else 0)
